name: 'Chromatic Deployment'

on:
  pull_request_review:
    branches: [v8]
    types: [submitted, edited]
    workflow_dispatch:

jobs:
  vrt-check:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the VRT script
        env:
          CHROMATIC_APP_CODE: ${{ secrets.CHROMATIC_APP_CODE }}
        run: ./docker/vrt "$CHROMATIC_APP_CODE"
        shell: bash
